Update .hound.suse.yml
New version from:
https://github.com/SUSE/style-guides/blob/master/rubocop-suse.yml
This will fix RuboCop error:
Error: obsolete parameter AlignWith (for Lint/EndAlignment)
found in crowbar-ha/.hound.suse.yml AlignWith has been renamed
to EnforcedStyleAlignWith.