horizon: Fix configuration loading for Monasca
Horizon and Monasca are typically installed on different nodes.
Therefore `monasca_server` variable has to be used to read Monasca
instance configuration values. Otherwise `monasca_cfg` could be empty
and result in the error:

  FATAL: NoMethodError: undefined method `[]' for nil:NilClass

  Relevant File Content:

  22>> grafana_password = monasca_cfg["db_grafana"]["password"]