fix undefined method [] for nil:NilClass (bsc#1013549)
Fix this error:

  Failed to apply the proposal: exception before calling chef
  (undefined method `[]' for nil:NilClass)

which was seen when a customer added two new nodes to a network
cluster (only running neutron agents and nothing else) and then
re-applied the Pacemaker proposal.

(cherry picked from commit eea2ba58018fbfeb3bb4beebf22caf2c76987af2)

https://bugzilla.suse.com/show_bug.cgi?id=1013549